name: Test Cronjob

on:
  schedule:
    # Every 5 minutes (minimum interval GitHub Actions allows)
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  hello:
    name: Echo Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "hello world"
