name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job-poller:
    uses: ./.github/workflows/job-poller.yml
    permissions:
      id-token: write
      contents: read
    secrets: inherit
