name: PR Workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  job-poller:
    uses: ./.github/workflows/job-poller.yml
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  pr-preview:
    uses: ./.github/workflows/pr-preview.yml
    needs: job-poller
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    secrets: inherit
